### ISSUE TITLE
DiskReadViolation in Sift.open

### ISSUE THREAD

**Issue by Turnsole** [SiftScience/sift-android#104]
We're following the example given in the README of this repo, and see that the Sift SDK is doing disk reads on the UI thread. This is evident if you turn on strict mode. 

```
11-16 09:47:26.429 1573 1573 D StrictMode: StrictMode policy violation; ~duration=319 ms: android.os.strictmode.DiskReadViolation
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at [libcore.io](http://libcore.io/).BlockGuardOs.access(BlockGuardOs.java:74)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at [libcore.io](http://libcore.io/).ForwardingOs.access(ForwardingOs.java:128)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7747)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at [java.io](http://java.io/).UnixFileSystem.checkAccess(UnixFileSystem.java:281)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at [java.io](http://java.io/).File.exists(File.java:813)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:751)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:742)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:698)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:923)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:545)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at siftscience.android.SiftImpl.<init>(SiftImpl.java:125)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at siftscience.android.SiftImpl.<init>(SiftImpl.java:97)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at siftscience.android.Sift.open(Sift.java:68)
11-16 09:47:26.429 1573 1573 D StrictMode: 	at siftscience.android.Sift.open(Sift.java:89)
```

**Comment by Turnsole** [comment]
A third of a second might not seem like much, but this is only one of many SDKs being initialized at app start, so it all adds up.

**Comment by SanoopC** [comment]
@Turnsole It just getting the preference object at the initial stage, and using SharedPreferenced$Editor.apply() instead of commit() during the operations, it's ok to leave SharedPreferences related stuff to read from disk on UI thread. The chance for an issue with it is low.

> Don't feel compelled to fix everything that StrictMode finds. In particular, many cases of disk access are often necessary during the normal activity lifecycle. Use StrictMode to find things you did by accident. Network requests on the UI thread are almost always a problem, though.

**Comment by Turnsole** [comment]
I understand that it's unlikely to cause the app to become unusable. But it is demonstrably costing valuable app start time unnecessarily.

**Comment by chad-cmb** [comment]
If the fix is to really use apply instead of commit, you should definitely make that change. Apply applies it immediately for all other instances of shared preferences to use, just doesn't block the save. Android guarantees that even on a power off, the preferences are saved.
