### ISSUE TITLE
Enable Proguard : java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient

### ISSUE THREAD

**Issue by mbpatel6245** [SiftScience/sift-android#105]
I have face some issues when we are enable the proguard then it gives below crashes when app startup. i have also added proguard rules that are mentioned in below link Can anyone help me on that what was the missing to fix this crashes?

https://github.com/SiftScience/sift-android/blob/master/sift/proguard-rules.pro

`java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~VTIc7iKWhf34pIMMdiknSg==/com.xyz.xyz-2gssJFgecMDkXCExyhtCmw==/base.apk!classes3.dex)
                                	at siftscience.android.AppStateCollector.startLocationUpdates(SourceFile:260)
                                	at siftscience.android.AppStateCollector.reconnectLocationServices(SourceFile:160)
                                	at siftscience.android.Sift.resume(SourceFile:166)
                                	at siftscience.android.Sift.resume(SourceFile:160)
                                	at com.xyz.xyz.di.AppInjector$init$1.onActivityResumed(SourceFile:55)
                                	at android.app.Application.dispatchActivityResumed(Application.java:431)
                                	at android.app.Activity.dispatchActivityResumed(Activity.java:1435)
                                	at android.app.Activity.onResume(Activity.java:1996)
                                	at androidx.fragment.app.FragmentActivity.onResume(SourceFile:310)
                                	at com.xyz.modulebase.base.BaseActivity.onResume(SourceFile:137)
                                	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
                                	at android.app.Activity.performResume(Activity.java:8437)
                                	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4763)
                                	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
                                	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
                                	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                	at android.os.Handler.dispatchMessage(Handler.java:106)
                                	at android.os.Looper.loopOnce(Looper.java:201)
                                	at android.os.Looper.loop(Looper.java:288)
                                	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                	at java.lang.reflect.Method.invoke(Native Method)
                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by viaskal-sift** [comment]
hi @mbpatel6245 , this issues was already addressed in the new version https://github.com/SiftScience/sift-android/releases/tag/v1.3.0, you can try that one
