### ISSUE TITLE
Fatal Exception: java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by TheLester** [SiftScience/sift-android#23]
On  Xiaomi Redmi Note 4 MI MAX i see such crash in my crashlytics dashboard:

```
Fatal Exception: java.lang.NoSuchFieldError: No static field a of type Lorg/apache/commons/lang3/builder/ToStringStyle; in class Lorg/apache/commons/lang3/builder/ToStringStyle; or its superclasses (declaration of 'org.apache.commons.lang3.builder.ToStringStyle' appears in /system/framework/framework.jar:classes2.dex)
       at org.apache.commons.lang3.builder.ToStringBuilder.(ToStringBuilder.java)
       at com.sift.api.representations.MobileEventJson.toString(MobileEventJson.java:173)
       at siftscience.android.Queue.append(Queue.java:199)
       at siftscience.android.DevicePropertiesCollector.collect(DevicePropertiesCollector.java:95)
       at siftscience.android.Sift.collect(Sift.java:69)
       at com.phrendly.screens.splash.SplashActivity.initSiftScience(SplashActivity.java:147)
       at com.phrendly.screens.splash.SplashActivity.onCreate(SplashActivity.java:40)
       at android.app.Activity.performCreate(Activity.java:6288)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2500)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613)
       at android.app.ActivityThread.access$900(ActivityThread.java:180)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
```

**Comment by TheLester** [comment]
I think you should add pro-guard rule for org.apache.commons.lang3

**Comment by quanpod** [comment]
@TheLester Thanks for the report - @garylee1 took a look at this earlier this week, should hear back from him next week.

**Comment by garylee1** [comment]
@TheLester we should be able to add that ProGuard rule with the next release. Thanks for the report!

**Comment by garylee1** [comment]
please hold off – we're fixing a small issue related to deserializing archived configs. the fix will be released soon with 0.9.10.

**Comment by garylee1** [comment]
0.9.10 has been released – please skip over 0.9.9
