### ISSUE TITLE
Crash on background Apps (Uploader)

### ISSUE THREAD

**Issue by gondekr** [SiftScience/sift-android#24]
There's a big number of occurences of this error on my Crashlytics dashboard

Currently using version 0.9.3

```
Fatal Exception: java.util.concurrent.RejectedExecutionException
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@9bb6199 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@93c86fe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2] 
```

Heres the stack:
```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@9bb6199 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@93c86fe[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:527)
       at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:626)
       at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:594)
       at siftscience.android.Uploader.upload(Uploader.java:158)
       at siftscience.android.Sift.upload(Sift.java:430)
       at siftscience.android.Sift$2.requestUpload(Sift.java:261)
       at siftscience.android.Queue.append(Queue.java:204)
       at siftscience.android.AppStateCollector.collect(AppStateCollector.java:75)
       at siftscience.android.AppStateCollector.onConnected(AppStateCollector.java:226)
       at com.google.android.gms.common.internal.zzac.zzn(Unknown Source)
       at com.google.android.gms.internal.zzbcp.zzm(Unknown Source)
       at com.google.android.gms.internal.zzbcd.zzpY(Unknown Source)
       at com.google.android.gms.internal.zzbcd.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzbcx.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzbbi.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzaa.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzn.zzrj(Unknown Source)
       at com.google.android.gms.common.internal.zze.zzs(Unknown Source)
       at com.google.android.gms.common.internal.zzi.zzrk(Unknown Source)
       at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by garylee1** [comment]
Hi, thanks for the report. We're currently on v0.9.8 and this issue was fixed quite some time ago – please see https://github.com/SiftScience/sift-android/issues/5.

**Comment by gondekr** [comment]
Thanks, sorry bout that 😅
