### ISSUE TITLE
OOM Error on Queue.archive() calling

### ISSUE THREAD

**Issue by pkovalenko** [SiftScience/sift-android#31]
SiftScience version to 0.9.10.
On samsung SM-N950U, Samsung S7, Samsung SM-G950U, LG V10 (Android 5, Android 7), I see crashes with next stacktrace.
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 155189256 byte allocation with 16777216 free bytes and 112MB until OOM
       at java.util.Arrays.copyOf(Arrays.java:3352)
       at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:417)
       at java.lang.StringBuffer.append(StringBuffer.java:237)
       at java.io.StringWriter.write(StringWriter.java:112)
       at com.google.gson.stream.JsonWriter.string(JsonWriter.java:591)
       at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
       at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417)
       at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:405)
       at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:389)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
       at com.google.gson.Gson.toJson(Gson.java:669)
       at com.google.gson.Gson.toJson(Gson.java:648)
       at com.google.gson.Gson.toJson(Gson.java:603)
       at com.google.gson.Gson.toJson(Gson.java:583)
       at siftscience.android.Queue.archive(Queue.java:171)
       at siftscience.android.Sift.save(Sift.java:376)
       at com.application.SplashActivity.onPause(SplashActivity.java:58)
       at android.app.Activity.performPause(Activity.java:7103)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1330)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4126)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4103)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4066)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4024)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

Could you please take a look at this issue. Thank you!

**Comment by garylee1** [comment]
@pkovalenko Thanks for the report – this has been reported with using GSON on old devices. going to look into streaming this so it doesn't take up heap space. Hope to get a fix out soon; will keep you updated!

**Comment by garylee1** [comment]
Actually – @pkovalenko would you mind sending a message to support@siftscience.com referencing this issue? It's curious that we'd be trying to write a string that large and I'd like to follow up on exactly what might be happening here with your integration.

**Comment by JayyyR** [comment]
Happens to us too, any updates on a fix for this?

**Comment by quanpod** [comment]
Thanks @JayyyR - can you also send a note to support?  Want to connect over email so we can get some more details. cc @garylee1

**Comment by pkovalenko** [comment]
@garylee1 @quanpod Hi, do you have any updates? We continue to receive crash reports with this issue.

**Comment by garylee1** [comment]
@pkovalenko Thank you for your patience — I will try to have a fix out this week.

**Comment by garylee1** [comment]
@pkovalenko @JayyyR I've just released https://github.com/SiftScience/sift-android/releases/tag/v0.9.13 which hopefully addresses this by decreasing the batch size by 75%. Please let me know how this works out.

**Comment by pkovalenko** [comment]
@garylee1 Thank you very mutch. We`ll update version in our app and let you know result.

**Comment by JayyyR** [comment]
Thanks! We'll try it as well

**Comment by garylee1** [comment]
@pkovalenko @JayyyR Please hold on integrating 0.9.13 — I need to make a small patch.

**Comment by JayyyR** [comment]
@garylee1 I'll hold off

**Comment by JayyyR** [comment]
@garylee1 any updates?

**Comment by garylee1** [comment]
@JayyyR We're almost at the end of a big release that addresses this and several other things. I'm hoping to get it out by the end of next week. Will keep you posted.

**Comment by JayyyR** [comment]
okay great, thanks for the update!

**Comment by falcon4ever** [comment]
Any updates on a bug fix?

**Comment by garylee1** [comment]
@falcon4ever We're starting code review for this fix – hope to have it out in the next few days! The new release will address this and generally use a much more performant/sane concurrency model, as well as addressing functionality gaps we've collected over the past few months of beta. It will require minor integration changes. I'll keep all of you in the loop.

**Comment by JayyyR** [comment]
Hi @garylee1 , sorry to keep bothering but any updates here? This is still our #1 crash. We should not be on 9.13, correct? We're still on 9.12

**Comment by garylee1** [comment]
@JayyyR Apologies for the delay – I was not able to get this out before being out of office, but I'm targeting end-of-day today for the new release.

**Comment by garylee1** [comment]
@pkovalenko @falcon4ever @JayyyR we've just released a significant upgrade to the SDK and have changed the archive, upload, and batching policy to hopefully address this issue (among many other improvements). The release can be found here:

https://github.com/SiftScience/sift-android/releases/tag/v0.10.0-beta

Please observe the release notes – there are a few breaking changes that require very minor integration tweaks and some optional new features as well. Note that it is a substantial rewrite and while we've tested it thoroughly and expect it to be much more stable, please do take special care in testing it. Thank you all for your patience.

**Comment by JayyyR** [comment]
thanks!

**Comment by JayyyR** [comment]
@garylee1 it doesn't look like Sift.collect() is being called on a separate thread anymore. In the old SDK, you were running deviceProperties.collect() in a different thread. Now it's not anymore in 0.10.0-beta. Is this intentional? Or maybe I'm missing something?

When collect() wasn't happening on a new thread in an old sdk, we were seeing very slow activity launch times. I just want to make sure the same thing won't happen again with 0.10.0

**Comment by garylee1** [comment]
@JayyyR ah, okay – we were pretty sure the slowness was coming from the unarchiving, which was synchronous before and with the latest release is not. we can also move the collection back to a background thread. i'll keep you posted.

**Comment by JayyyR** [comment]
ah so unarchiving is still asynchronous in 0.10?

**Comment by garylee1** [comment]
sorry, no – our profiling (and other reports) showed unarchiving (restoring the SDK state from disk) to be the launch bottleneck, so we changed that to be asynchronous. separately, we can also easily move collect() back to an AsyncTask if that was causing issues for your application.

**Comment by garylee1** [comment]
@JayyyR we just released [0.10.1-beta](https://github.com/SiftScience/sift-android/releases/tag/v0.10.1-beta) which moves `collect` back to AsyncTask

**Comment by garylee1** [comment]
@pkovalenko @falcon4ever please upgrade to the latest version – [0.10.1-beta](https://github.com/SiftScience/sift-android/releases/tag/v0.10.1-beta)

**Comment by garylee1** [comment]
excellent! @pkovalenko for reference, the latest is now [0.10.2-beta](https://github.com/SiftScience/sift-android/releases/tag/v0.10.2-beta)
