### ISSUE TITLE
Crash on AppStateCollector.onConnected

### ISSUE THREAD

**Issue by kaeawc** [SiftScience/sift-android#37]
Using the latest version of Sift Android SDK 0.9.11, observed a crash from a user on Kitkat (4.4.4) - HM NOTE 1LTETD

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@425b4e98 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4214d8e0[Shutting down, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 3]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:298)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
       at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:644)
       at siftscience.android.AppStateCollector.onConnected(SourceFile:250)
       at com.google.android.gms.common.internal.zzae.zzk(Unknown Source)
       at com.google.android.gms.common.api.internal.zzba.zzj(Unknown Source)
       at com.google.android.gms.common.api.internal.zzao.zzaie(Unknown Source)
       at com.google.android.gms.common.api.internal.zzao.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbi.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzt.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzac.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzn.zzakr(Unknown Source)
       at com.google.android.gms.common.internal.zze.zzw(Unknown Source)
       at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source)
       at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5052)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by garylee1** [comment]
thanks for the report! this is only a crash when backgrounding. we fixed this with https://github.com/SiftScience/sift-android/releases/tag/v0.9.12
