### ISSUE TITLE
Crash when App go to backgroung or Restore from backgroung.

### ISSUE THREAD

**Issue by pkovalenko** [SiftScience/sift-android#5]
I integrated SiftScience into my app. In my screen flow I have Activities and Fragments, than I used Custom Integration from docs.
Sometimes when app goes to the background or restore from the background, I get Crash with next stack trace:

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@815b2d4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1b1ec7d[Shutting down, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 1]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:527)
       at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:616)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:584)
       at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:530)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
       at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:56)
       at siftscience.android.Uploader.upload(Uploader.java:158)
       at siftscience.android.Sift.upload(Sift.java:430)
       at siftscience.android.Sift$2.requestUpload(Sift.java:263)
       at siftscience.android.Queue.append(Queue.java:204)
       at siftscience.android.AppStateCollector.collect(AppStateCollector.java:75)
       at siftscience.android.AppStateCollector.onConnected(AppStateCollector.java:226)
       at com.google.android.gms.common.internal.zzm.zzq(Unknown Source)
       at com.google.android.gms.internal.zzaat.zzo(Unknown Source)
       at com.google.android.gms.internal.zzaar.zzwi(Unknown Source)
       at com.google.android.gms.internal.zzaar.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzaav.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzaag.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzj.zzxG(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzb(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zze.zzxH(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

It happens not all time, only sometimes. I got this crashes on Samsung S5 and LG Nexus 5 devices.

Thank you.
```

**Comment by nickhurlburt** [comment]
@pkovalenko thanks for bringing this to our attention, we'll take a look.

**Comment by AnilRh** [comment]
Any update on this one @nickhurlburt?

**Comment by garylee1** [comment]
@AnilRh this should have been fixed with the latest release.

**Comment by garylee1** [comment]
https://github.com/SiftScience/sift-android/releases/tag/v0.9.4

**Comment by quanpod** [comment]
@pkovalenko @AnilRh let us know if this fixes the issue for you
