### ISSUE TITLE
Crash on GoogleApiClient.isConneted()

### ISSUE THREAD

**Issue by JayyyR** [SiftScience/sift-android#52]
We updated to the latest version 0.10.1-beta and now we're seeing a sift crash as our top issue

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnected()' on a null object reference
       at siftscience.android.AppStateCollector.collect(AppStateCollector.java:80)
       at siftscience.android.Sift$1.run(Sift.java:99)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```
Looks like the googleApiClient can be null

**Comment by quanpod** [comment]
Thanks @JayyyR - acknowledging the report.  Assigning @garylee1 to take a look.

**Comment by garylee1** [comment]
@JayyyR we've fixed this with https://github.com/SiftScience/sift-android/releases/tag/v0.10.2-beta !

**Comment by JayyyR** [comment]
Thanks, we'll give it a go
