### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by dmitry-novikov** [SiftScience/sift-android#61]
We have faced crash on `sift-android` version `0.9.13`:
```
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
       at com.google.gson.Gson.toJson(Gson.java:704)
       at com.google.gson.Gson.toJson(Gson.java:683)
       at com.google.gson.Gson.toJson(Gson.java:638)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at siftscience.android.Uploader$Batches.archive(Uploader.java:100)
       at siftscience.android.Uploader.archive(Uploader.java:172)
       at siftscience.android.Sift.save(Sift.java:373)
       at app.di.app.plugins.SiftPlugin$LifecycleCallbacks.onActivityPaused(SiftPlugin.kt:39)
       at android.app.Application.dispatchActivityPaused(Application.java:225)
       at android.app.Activity.onPause(Activity.java:1684)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:441)
       at app.platform.activity.BaseActivity.onPause(BaseActivity.kt:78)
       at app.Main$Activity.onPause(Main.kt:1011)
       at android.app.Activity.performPause(Activity.java:7129)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1429)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4057)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4034)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4008)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3982)
       at android.app.ActivityThread.-wrap15(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6695)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
```

**Comment by garylee1** [comment]
This has been fixed with all subsequent versions after 0.10.x – we just released 0.10.4 so please use that.
