### ISSUE TITLE
Sift throws  java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by 20ali20** [SiftScience/sift-android#73]
Implementing Sift as lifecycle handler in Application throws 
```
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter bundle
        at com.chownow.utils.siftScience.SiftScienceLifeCycleHandler.onActivityCreated(Unknown Source:7)
        at android.app.Application.dispatchActivityCreated(Application.java:373)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1207)
        at android.app.Activity.onCreate(Activity.java:1480)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at com.chownow.utils.navigation.ParentActivity.onCreate(ParentActivity.kt:31)
        at com.chownow.application.SplashActivity.onCreate(SplashActivity.kt:50)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-02-10 13:04:24.365 15884-15884/com.chownow.hudsonscafe E/CrashlyticsCore: Failed to execute task.
```

This is because Sift is made to be non-null. Please make it nullable. 

I checked and there was another issue making the same request and it seemed like the request was accepted and yet I see the similar issue happening now.

**Comment by viaskal-sift** [comment]
Hi @20ali20, based on the stacktrace provided we don't see any references to our SDK (classes should start with `siftscience.android.*`). So, the question is - could you please provide more information so that we are able to detect the problem?
