### ISSUE TITLE
Crash in Sift.open(this)

### ISSUE THREAD

**Issue by pkovalenko** [SiftScience/sift-android#9]
I updated SiftScience version to 0.9.4.
On samsung S5(API version 6), Samsung S8(API version 7), when I call Sift.open(this),  I got 
`java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzg, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
                                                                  at com.google.android.gms.common.api.GoogleApiClient$Builder.zza(Unknown Source)
                                                                  at com.google.android.gms.common.api.GoogleApiClient$Builder.zzvq(Unknown Source)
                                                                  at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                  at siftscience.android.AppStateCollector.<init>(AppStateCollector.java:62)
                                                                  at siftscience.android.Sift.open(Sift.java:56)
                                                                  at siftscience.android.Sift.open(Sift.java:45)`

Thank you.

**Comment by garylee1** [comment]
Hi – I believe this is due to a bug in mismatched Google Play APIs versions and there's no good solution on our end short of forcing dependency versions for our SDK clients (which is bad practice). Can you make sure that all `com.google.android.gms-play-services-*` dependencies you are using are on at least 9.8.0?

**Comment by pkovalenko** [comment]
Currently we use GMS version 10.2.4, I updated to latest 11.0.4 but got same crash.
I downgrade GMS version to 9.8.0 and it works on old version. 
But we use some  some Firebase Messaging and Google Account functional from latest versions and we cannot use old version of GMS.

Thank you.

**Comment by AnilRh** [comment]
Any update on this issue @garylee1 ?

**Comment by garylee1** [comment]
@AnilRh we'll put it on our roadmap to address the near future. does it sound like a reasonable fix to configure gradle to allow multiple versions of the same library, and force the one our SDK is using to call the 9.8.0 APIs everywhere?

**Comment by pkovalenko** [comment]
Problem was solved by adding 
`compile "com.google.android.gms:play-services-location:$rootProject.gmsVersion"`
to dependency list of my application module
