### ISSUE TITLE
NullPointerException crash - getIpAddresses

### ISSUE THREAD

**Issue by ericntd** [SiftScience/sift-android#94]
I saw https://github.com/SiftScience/sift-android/issues/67 and we are using v0.10.5 but the crash is still happening
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.List java.net.NetworkInterface.childs' on a null object reference
       at java.net.NetworkInterface.getAll(NetworkInterface.java:498)
       at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:398)
       at siftscience.android.AppStateCollector.getIpAddresses(AppStateCollector.java:171)
       at siftscience.android.AppStateCollector.get(AppStateCollector.java:150)
       at siftscience.android.AppStateCollector.doCollect(AppStateCollector.java:127)
       at siftscience.android.AppStateCollector.onConnected(AppStateCollector.java:264)
       at com.google.android.gms.common.internal.zah.zaa(zah.java:30)
       at com.google.android.gms.common.api.internal.zaap.zaa(zaap.java:295)
       at com.google.android.gms.common.api.internal.zaad.zaf(zaad.java:130)
       at com.google.android.gms.common.api.internal.zaad.zaa(zaad.java:108)
       at com.google.android.gms.common.api.internal.zaax.onConnected(zaax.java:105)
       at com.google.android.gms.common.api.internal.zap.onConnected(zap.java:5)
       at com.google.android.gms.common.internal.zag.onConnected(zag.java:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(BaseGmsClient.java:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(BaseGmsClient.java:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(BaseGmsClient.java:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(BaseGmsClient.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8283)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

It's happening on Android 11 exclusively
Device varies
![Screen Shot 2021-11-17 at 9 56 29 AM](https://user-images.githubusercontent.com/19919208/142224300-49abc40d-9dd0-4ab6-950a-5a3214381453.png)

**Comment by ericntd** [comment]
Does not look like your issue but Android's https://issuetracker.google.com/issues/204913332
